In [1]:
import numpy as np

In [263]:
def initialization(X):
    n, m = X.shape
    w = np.random.randn(n)
    b = np.random.randn(1)
    return n,m,w,b

In [264]:
def prop(X,y,w,b):
    a = w@X+b
    dw = X@(a-y)
    db = sum(a-y)
    return dw, db

In [265]:
def cost(a,y):
    return np.sum((a-y)**2)

In [266]:
def update(dw,db,w,b,alpha):
    w = w-alpha*dw
    b = b-alpha*db
    return w,b


In [267]:
def prediction(w,b,X):
    return w@X+b

In [279]:
def linear_regression(X, y, N, alpha): # X: np.array n*m; y: 1*m;    n: No. of variables; m:No of Observations; N: iteration; alpha: learning rate
    n,m,w,b = initialization(X)
    for i in range(N):
        dw, db = prop(X,y,w,b)
        w, b = update(dw,db,w,b,alpha)
        cost = sum((w@X+b-y)**2)
        print('cost is', cost, 'w is', w)
    a = prediction(w,b,X)
    return {'w':w,'b':b,'pred':a}

In [280]:
X = np.array([[0,2,3,4,6,8],[2,3,5,6,9,7],[3,5,1,6,8,0]])
y = np.array([7,14,15,10,11,12])

In [287]:
linear_regression(X,y,10000,0.001)

cost is 318.2326030449385 w is [ 0.3613043   1.19472455 -0.70948605]
cost is 224.2081265128396 w is [ 0.45756656  1.35397788 -0.55776288]
cost is 190.1997708475052 w is [ 0.5029819   1.44431167 -0.45689293]
cost is 176.58986808702005 w is [ 0.51936811  1.49483377 -0.38620033]
cost is 170.03689584728505 w is [ 0.51935328  1.52241419 -0.33366143]
cost is 166.0357796836029 w is [ 0.5102381   1.53682735 -0.2922713 ]
cost is 163.05427288299865 w is [ 0.49623534  1.54373377 -0.25793664]
cost is 160.5613563743666 w is [ 0.47976831  1.54640895 -0.22825408]
cost is 158.36419551193546 w is [ 0.46222369  1.54674579 -0.2018016 ]
cost is 156.38506427588706 w is [ 0.44438804  1.54583584 -0.17772767]
cost is 154.58620629107494 w is [ 0.42670081  1.5443063  -0.15551289]
cost is 152.94444740361521 w is [ 0.40940104  1.54251541 -0.13483175]
cost is 151.442547551616 w is [ 0.39261233  1.54066574 -0.1154724 ]
cost is 150.06619164810462 w is [ 0.37639215  1.53886983 -0.09729004]
cost is 148.80288635301446 

cost is 67.48414408948574 w is [-0.6797085   1.73776825 -0.28383317]
cost is 67.43526718422966 w is [-0.67973944  1.7371945  -0.28408648]
cost is 67.38647749596089 w is [-0.67976872  1.73661958 -0.2843389 ]
cost is 67.33777482195458 w is [-0.67979637  1.73604351 -0.28459041]
cost is 67.28915896016217 w is [-0.67982237  1.73546629 -0.28484102]
cost is 67.24062970920865 w is [-0.67984674  1.73488792 -0.28509073]
cost is 67.19218686838936 w is [-0.67986949  1.73430841 -0.28533955]
cost is 67.14383023766737 w is [-0.67989061  1.73372776 -0.28558748]
cost is 67.09555961767047 w is [-0.67991012  1.73314598 -0.28583452]
cost is 67.04737480968818 w is [-0.67992802  1.73256307 -0.28608067]
cost is 66.99927561566899 w is [-0.67994431  1.73197904 -0.28632593]
cost is 66.9512618382175 w is [-0.67995899  1.7313939  -0.28657031]
cost is 66.90333328059144 w is [-0.67997209  1.73080764 -0.28681382]
cost is 66.85548974669916 w is [-0.67998359  1.73022028 -0.28705644]
cost is 66.80773104109647 w is [-0.

cost is 47.743395112639895 w is [-0.51251681  1.25663184 -0.33629372]
cost is 47.72673678863331 w is [-0.51215699  1.25591371 -0.33628068]
cost is 47.71010389565335 w is [-0.51179715  1.25519584 -0.33626753]
cost is 47.69349639329903 w is [-0.5114373   1.25447822 -0.33625426]
cost is 47.676914241241626 w is [-0.51107743  1.25376087 -0.33624088]
cost is 47.66035739922448 w is [-0.51071754  1.25304377 -0.33622738]
cost is 47.643825827062734 w is [-0.51035765  1.25232694 -0.33621376]
cost is 47.62731948464331 w is [-0.50999773  1.25161036 -0.33620004]
cost is 47.61083833192462 w is [-0.50963781  1.25089405 -0.33618619]
cost is 47.59438232893655 w is [-0.50927788  1.250178   -0.33617224]
cost is 47.577951435780115 w is [-0.50891793  1.24946221 -0.33615817]
cost is 47.561545612627384 w is [-0.50855798  1.24874668 -0.33614399]
cost is 47.54516481972133 w is [-0.50819801  1.24803142 -0.33612969]
cost is 47.52880901737566 w is [-0.50783804  1.24731642 -0.33611529]
cost is 47.51247816597462 w i

cost is 40.69879006923249 w is [-0.28908016  0.84407602 -0.31495218]
cost is 40.69278449598912 w is [-0.28879662  0.84357803 -0.31491496]
cost is 40.68678794834179 w is [-0.28851324  0.84308036 -0.31487774]
cost is 40.68080041267855 w is [-0.28823003  0.84258302 -0.31484054]
cost is 40.67482187540822 w is [-0.28794698  0.84208601 -0.31480334]
cost is 40.66885232296037 w is [-0.28766409  0.84158932 -0.31476615]
cost is 40.662891741785266 w is [-0.28738137  0.84109295 -0.31472896]
cost is 40.656940118353845 w is [-0.2870988   0.84059691 -0.31469178]
cost is 40.65099743915772 w is [-0.28681641  0.84010119 -0.3146546 ]
cost is 40.645063690709094 w is [-0.28653417  0.8396058  -0.31461743]
cost is 40.63913885954074 w is [-0.2862521   0.83911073 -0.31458027]
cost is 40.633222932205996 w is [-0.28597019  0.83861599 -0.31454312]
cost is 40.62731589527872 w is [-0.28568845  0.83812156 -0.31450597]
cost is 40.62141773535319 w is [-0.28540686  0.83762747 -0.31446883]
cost is 40.61552843904423 w is

cost is 38.25137877207089 w is [-0.1415371   0.58895783 -0.29399133]
cost is 38.24904846561522 w is [-0.14134888  0.58863623 -0.29396306]
cost is 38.2467216567706 w is [-0.14116079  0.58831487 -0.29393481]
cost is 38.244398340285564 w is [-0.14097283  0.58799373 -0.29390658]
cost is 38.242078510916556 w is [-0.14078501  0.58767283 -0.29387836]
cost is 38.23976216342786 w is [-0.14059731  0.58735215 -0.29385016]
cost is 38.23744929259173 w is [-0.14040975  0.58703171 -0.29382198]
cost is 38.23513989318819 w is [-0.14022232  0.5867115  -0.29379381]
cost is 38.23283396000513 w is [-0.14003502  0.58639152 -0.29376566]
cost is 38.230531487838284 w is [-0.13984785  0.58607177 -0.29373753]
cost is 38.228232471491225 w is [-0.13966081  0.58575226 -0.29370941]
cost is 38.225936905775285 w is [-0.13947391  0.58543297 -0.29368131]
cost is 38.22364478550967 w is [-0.13928713  0.58511391 -0.29365323]
cost is 38.22135610552129 w is [-0.13910048  0.58479508 -0.29362516]
cost is 38.219070860644926 w i

cost is 37.246207483817734 w is [-0.03854437  0.41381964 -0.27818983]
cost is 37.245385742583366 w is [-0.03843034  0.41362645 -0.27817206]
cost is 37.24456523455958 w is [-0.0383164   0.41343341 -0.27815429]
cost is 37.24374595789559 w is [-0.03820254  0.41324051 -0.27813654]
cost is 37.24292791074341 w is [-0.03808877  0.41304775 -0.2781188 ]
cost is 37.242111091257854 w is [-0.03797508  0.41285514 -0.27810107]
cost is 37.24129549759645 w is [-0.03786147  0.41266267 -0.27808336]
cost is 37.24048112791952 w is [-0.03774795  0.41247035 -0.27806566]
cost is 37.23966798039018 w is [-0.03763451  0.41227816 -0.27804797]
cost is 37.23885605317424 w is [-0.03752116  0.41208612 -0.27803029]
cost is 37.23804534444031 w is [-0.03740788  0.41189422 -0.27801263]
cost is 37.23723585235972 w is [-0.0372947   0.41170247 -0.27799497]
cost is 37.236427575106546 w is [-0.03718159  0.41151085 -0.27797734]
cost is 37.235620510857665 w is [-0.03706857  0.41131938 -0.27795971]
cost is 37.234814657792604 w 

cost is 36.89554817332032 w is [ 0.02245278  0.31060863 -0.26862743]
cost is 36.89525267334102 w is [ 0.02252152  0.31049241 -0.2686166 ]
cost is 36.89495761682257 w is [ 0.02259022  0.31037629 -0.26860579]
cost is 36.89466300309946 w is [ 0.02265887  0.31026025 -0.26859498]
cost is 36.89436883150717 w is [ 0.02272746  0.3101443  -0.26858418]
cost is 36.894075101382214 w is [ 0.02279601  0.31002844 -0.26857339]
cost is 36.893781812062045 w is [ 0.0228645   0.30991266 -0.2685626 ]
cost is 36.89348896288515 w is [ 0.02293294  0.30979697 -0.26855183]
cost is 36.89319655319101 w is [ 0.02300134  0.30968136 -0.26854106]
cost is 36.89290458232009 w is [ 0.02306967  0.30956585 -0.2685303 ]
cost is 36.892613049613814 w is [ 0.02313796  0.30945042 -0.26851955]
cost is 36.89232195441464 w is [ 0.0232062   0.30933507 -0.2685088 ]
cost is 36.89203129606599 w is [ 0.02327439  0.30921981 -0.26849807]
cost is 36.89174107391227 w is [ 0.02334252  0.30910464 -0.26848734]
cost is 36.89145128729886 w is 

cost is 36.77030588901027 w is [ 0.05881831  0.24915963 -0.26289322]
cost is 36.770198341743814 w is [ 0.05885985  0.24908946 -0.26288666]
cost is 36.77009095587488 w is [ 0.05890136  0.24901935 -0.26288011]
cost is 36.76998373116125 w is [ 0.05894284  0.24894928 -0.26287356]
cost is 36.76987666736112 w is [ 0.05898428  0.24887927 -0.26286702]
cost is 36.76976976423291 w is [ 0.0590257   0.24880931 -0.26286048]
cost is 36.769663021535585 w is [ 0.05906708  0.2487394  -0.26285395]
cost is 36.76955643902836 w is [ 0.05910843  0.24866954 -0.26284742]
cost is 36.76945001647081 w is [ 0.05914975  0.24859974 -0.26284089]
cost is 36.76934375362292 w is [ 0.05919104  0.24852999 -0.26283437]
cost is 36.76923765024504 w is [ 0.0592323   0.24846029 -0.26282786]
cost is 36.76913170609777 w is [ 0.05927353  0.24839065 -0.26282135]
cost is 36.76902592094223 w is [ 0.05931473  0.24832105 -0.26281485]
cost is 36.76892029453979 w is [ 0.0593559   0.24825151 -0.26280835]
cost is 36.76881482665218 w is [

cost is 36.723612346392144 w is [ 0.08149667  0.21085359 -0.25931132]
cost is 36.72357487270296 w is [ 0.0815212   0.21081216 -0.25930744]
cost is 36.72353745525102 w is [ 0.08154571  0.21077076 -0.25930357]
cost is 36.723500093951884 w is [ 0.08157021  0.21072939 -0.2592997 ]
cost is 36.72346278872132 w is [ 0.08159468  0.21068805 -0.25929583]
cost is 36.72342553947519 w is [ 0.08161914  0.21064675 -0.25929197]
cost is 36.72338834612944 w is [ 0.08164358  0.21060547 -0.25928811]
cost is 36.72335120860023 w is [ 0.081668    0.21056422 -0.25928425]
cost is 36.72331412680375 w is [ 0.0816924   0.21052301 -0.2592804 ]
cost is 36.7232771006564 w is [ 0.08171679  0.21048183 -0.25927654]
cost is 36.72324013007462 w is [ 0.08174115  0.21044067 -0.25927269]
cost is 36.723203214975065 w is [ 0.0817655   0.21039955 -0.25926885]
cost is 36.72316635527443 w is [ 0.08178983  0.21035846 -0.259265  ]
cost is 36.72312955088962 w is [ 0.08181414  0.2103174  -0.25926116]
cost is 36.723092801737614 w is 

cost is 36.707757141231596 w is [ 0.09443261  0.18900591 -0.25726721]
cost is 36.707743461644334 w is [ 0.09444743  0.18898088 -0.25726487]
cost is 36.70772980258617 w is [ 0.09446224  0.18895586 -0.25726253]
cost is 36.70771616402634 w is [ 0.09447704  0.18893087 -0.25726019]
cost is 36.70770254593405 w is [ 0.09449183  0.18890589 -0.25725785]
cost is 36.707688948278644 w is [ 0.09450661  0.18888093 -0.25725551]
cost is 36.70767537102936 w is [ 0.09452138  0.18885599 -0.25725318]
cost is 36.707661814155635 w is [ 0.09453614  0.18883107 -0.25725085]
cost is 36.70764827762687 w is [ 0.09455088  0.18880617 -0.25724852]
cost is 36.70763476141256 w is [ 0.09456562  0.18878128 -0.25724619]
cost is 36.70762126548218 w is [ 0.09458034  0.18875642 -0.25724386]
cost is 36.707607789805316 w is [ 0.09459505  0.18873157 -0.25724154]
cost is 36.70759433435157 w is [ 0.09460975  0.18870674 -0.25723922]
cost is 36.707580899090594 w is [ 0.09462444  0.18868193 -0.25723689]
cost is 36.70756748399206 w 

cost is 36.70181314053448 w is [ 0.10253223  0.17532678 -0.25598716]
cost is 36.70180838118234 w is [ 0.10254097  0.17531202 -0.25598578]
cost is 36.701803628972606 w is [ 0.10254971  0.17529726 -0.2559844 ]
cost is 36.701798883894575 w is [ 0.10255844  0.17528252 -0.25598302]
cost is 36.70179414593754 w is [ 0.10256716  0.17526778 -0.25598164]
cost is 36.70178941509082 w is [ 0.10257588  0.17525306 -0.25598026]
cost is 36.70178469134374 w is [ 0.10258459  0.17523835 -0.25597888]
cost is 36.70177997468564 w is [ 0.10259329  0.17522365 -0.25597751]
cost is 36.701775265105894 w is [ 0.10260199  0.17520896 -0.25597613]
cost is 36.70177056259386 w is [ 0.10261068  0.17519428 -0.25597476]
cost is 36.70176586713895 w is [ 0.10261937  0.17517961 -0.25597339]
cost is 36.70176117873057 w is [ 0.10262805  0.17516496 -0.25597201]
cost is 36.70175649735814 w is [ 0.10263672  0.17515031 -0.25597064]
cost is 36.70175182301111 w is [ 0.10264538  0.17513568 -0.25596927]
cost is 36.701747155678916 w is

cost is 36.69974016535687 w is [ 0.1073253   0.16723201 -0.25522964]
cost is 36.69973851694413 w is [ 0.10733045  0.16722332 -0.25522883]
cost is 36.69973687100518 w is [ 0.10733559  0.16721464 -0.25522801]
cost is 36.69973522753632 w is [ 0.10734073  0.16720596 -0.2552272 ]
cost is 36.69973358653382 w is [ 0.10734586  0.16719729 -0.25522639]
cost is 36.69973194799398 w is [ 0.10735099  0.16718863 -0.25522558]
cost is 36.69973031191314 w is [ 0.10735612  0.16717997 -0.25522477]
cost is 36.6997286782876 w is [ 0.10736124  0.16717132 -0.25522396]
cost is 36.69972704711363 w is [ 0.10736636  0.16716267 -0.25522315]
cost is 36.69972541838759 w is [ 0.10737147  0.16715404 -0.25522234]
cost is 36.699723792105814 w is [ 0.10737658  0.1671454  -0.25522153]
cost is 36.69972216826462 w is [ 0.10738169  0.16713678 -0.25522073]
cost is 36.69972054686034 w is [ 0.1073868   0.16712816 -0.25521992]
cost is 36.699718927889315 w is [ 0.1073919   0.16711955 -0.25521911]
cost is 36.699717311347904 w is [

cost is 36.699040316518264 w is [ 0.11005111  0.16262856 -0.25479884]
cost is 36.6990397183773 w is [ 0.11005421  0.16262332 -0.25479835]
cost is 36.699039121133964 w is [ 0.1100573   0.16261809 -0.25479786]
cost is 36.699038524786936 w is [ 0.1100604   0.16261287 -0.25479737]
cost is 36.69903792933485 w is [ 0.11006349  0.16260764 -0.25479688]
cost is 36.699037334776364 w is [ 0.11006658  0.16260242 -0.25479639]
cost is 36.69903674111013 w is [ 0.11006967  0.16259721 -0.2547959 ]
cost is 36.69903614833483 w is [ 0.11007275  0.162592   -0.25479541]
cost is 36.699035556449104 w is [ 0.11007584  0.16258679 -0.25479493]
cost is 36.69903496545163 w is [ 0.11007892  0.16258159 -0.25479444]
cost is 36.699034375341085 w is [ 0.110082    0.16257639 -0.25479395]
cost is 36.69903378611612 w is [ 0.11008507  0.16257119 -0.25479347]
cost is 36.699033197775414 w is [ 0.11008815  0.162566   -0.25479298]
cost is 36.699032610317616 w is [ 0.11009122  0.16256081 -0.2547925 ]
cost is 36.699032023741466 

cost is 36.69878125019346 w is [ 0.1117375   0.15978051 -0.25453231]
cost is 36.69878104083652 w is [ 0.11173933  0.15977741 -0.25453202]
cost is 36.698780831793776 w is [ 0.11174117  0.15977431 -0.25453173]
cost is 36.69878062306474 w is [ 0.111743    0.15977122 -0.25453144]
cost is 36.69878041464895 w is [ 0.11174483  0.15976813 -0.25453115]
cost is 36.69878020654592 w is [ 0.11174666  0.15976504 -0.25453086]
cost is 36.69877999875519 w is [ 0.11174848  0.15976196 -0.25453057]
cost is 36.6987797912763 w is [ 0.11175031  0.15975888 -0.25453028]
cost is 36.698779584108784 w is [ 0.11175213  0.15975579 -0.25452999]
cost is 36.69877937725217 w is [ 0.11175396  0.15975272 -0.25452971]
cost is 36.698779170705976 w is [ 0.11175578  0.15974964 -0.25452942]
cost is 36.69877896446975 w is [ 0.1117576   0.15974657 -0.25452913]
cost is 36.69877875854303 w is [ 0.11175942  0.15974349 -0.25452884]
cost is 36.69877855292535 w is [ 0.11176123  0.15974042 -0.25452856]
cost is 36.698778347616226 w is 

cost is 36.698692365774725 w is [ 0.11270892  0.15813993 -0.25437878]
cost is 36.698692289807724 w is [ 0.11271002  0.15813807 -0.2543786 ]
cost is 36.69869221395473 w is [ 0.11271113  0.1581362  -0.25437843]
cost is 36.69869213821558 w is [ 0.11271223  0.15813434 -0.25437825]
cost is 36.6986920625901 w is [ 0.11271333  0.15813248 -0.25437808]
cost is 36.6986919870781 w is [ 0.11271443  0.15813062 -0.25437791]
cost is 36.69869191167943 w is [ 0.11271553  0.15812876 -0.25437773]
cost is 36.698691836393905 w is [ 0.11271663  0.1581269  -0.25437756]
cost is 36.69869176122135 w is [ 0.11271773  0.15812505 -0.25437738]
cost is 36.69869168616162 w is [ 0.11271883  0.15812319 -0.25437721]
cost is 36.69869161121451 w is [ 0.11271993  0.15812134 -0.25437704]
cost is 36.698691536379904 w is [ 0.11272102  0.15811949 -0.25437686]
cost is 36.698691461657596 w is [ 0.11272212  0.15811764 -0.25437669]
cost is 36.69869138704742 w is [ 0.11272321  0.15811579 -0.25437652]
cost is 36.69869131254923 w is 

{'w': array([ 0.1131512 ,  0.15739299, -0.25430888]),
 'b': array([11.20100275]),
 'pred': array([10.7528621 , 10.62793974, 12.07311243, 11.07211224, 11.26197587,
        13.20796329])}

# Approach 2

In [288]:
def linear_regression2(X, y):
    n, m = X.shape
    one = np.ones(m).reshape(1,m)
    X1 = np.concatenate((one,X),axis=0)
    beta = y@X1.T@np.linalg.inv(X1@X1.T)
    return beta, beta@X1

In [289]:
linear_regression2(X, y)

(array([11.20637726,  0.11418057,  0.15565455, -0.25414619]),
 array([10.7552478 , 10.63097112, 12.07304554, 11.07214972, 11.25918214,
        13.20940368]))

# Approach 3

In [65]:
from sklearn.linear_model import LinearRegression

In [236]:
reg = LinearRegression().fit(X.T,y)

In [237]:
reg.coef_

array([ 0.11418057,  0.15565455, -0.25414619])

In [238]:
reg.intercept_

11.206377260731667

In [240]:
reg.predict(X.T)

array([10.7552478 , 10.63097112, 12.07304554, 11.07214972, 11.25918214,
       13.20940368])

In [283]:
sum((reg.predict(X.T)-y)**2)

36.698641745151676